import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider"
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import "../globals.css";
import BackgroundLayout from "@/components/BackgroundWrapper";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import { routing } from "@/i18n/routing";
import { Toaster } from "@/components/ui/sonner"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CV - Elkasmi Fatima Zahra",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} z-0 antialiased`}
        >
            <BackgroundLayout>
             <MaxWidthWrapper>
              <ThemeProvider 
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
               >
                <NextIntlClientProvider>
                  {children}
                </NextIntlClientProvider>
                <Toaster />
              </ThemeProvider>
            </MaxWidthWrapper>
          </BackgroundLayout>
      </body>
    </html>
  );
}
